os: osx
osx_image: xcode10.2

script:
  - brew uninstall --force --ignore-dependencies $(brew list) || exit 1
  - brew update
  - brew cleanup -s
  - brew install autoconf boost@1.57 fontconfig gdbm glib harfbuzz jpeg libffi libtiff openssl pixman python@2 sqlite automake freetype gdk-pixbuf gmp icu4c libcroco libpng libtool pango pkg-config qt watch berkeley-db@4 cairo fribidi gettext graphite2 iperf libevent librsvg miniupnpc pcre protobuf readline
  - export LDFLAGS+="-L/usr/local/opt/boost@1.57/lib"
  - export CPPFLAGS+="-I/usr/local/opt/boost@1.57/include"
  - export LDFLAGS+=-L/usr/local/opt/openssl/lib
  - export CPPFLAGS+=-I/usr/local/opt/openssl/include
  - ./autogen.sh && ./configure --with-gui=qt5 --disable-tests && make -j4 && make deploy
  - ls
