language: minimal
sudo: required
services:
#   - docker
cache:
  ccache: true
  directories:
    - depends/built
    - depends/sdk-sources
    - $HOME/.ccache
stages:
#  - ubuntu16
#  - ubuntu18
  - windows32
  #- windows64
  #- osx
env:
  global:
    - MAKEJOBS=-j3
    - RUN_UNIT_TESTS=true
    - RUN_FUNCTIONAL_TESTS=false # Not Yet Implemented
    - RUN_BENCH=false # Set to true for any one job that has debug enabled, to quickly check bench is not crashing or hitting assertions
    - DOCKER_NAME_TAG=ubuntu:18.04
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - WINEDEBUG=fixme-all
    - DOCKER_PACKAGES="build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev git make gcc g++ autoconf libboost-all-dev software-properties-common libzmq3-dev libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libzmq3-dev libqrencode-dev autoconf libcurl4-openssl-dev libgmp-dev libleveldb-dev libmicrohttpd-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler"
before_install:
install:
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES $DOCKER_PACKAGES
before_script:
  - export -f travis_fold
  - source .travis/before_script.sh
script:
  - set -o errexit; source .travis/install.sh
after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
before_deploy:
  - export TRAVIS_TAG="preview"
deploy:
  provider: releases
  api_key: $OAUTH
  file: "$NAME.tar.gz"
  skip_cleanup: true
  draft: true
jobs:
  include:
#     - stage: ubuntu16
#       dist: xenial
#       env: >-
#         HOST=x86_64-86-linux-gnu
#         NAME=ubuntu16.04-$HOST
#         PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev libprotobuf-dev"
#         DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1"
#         GOAL="install"
#         BITCOIN_CONFIG="--disable-tests --disable-gui-tests --disable-bench --enable-experimental-asm CFLAGS=-fPIC CXXFLAGS=-fPIC --enable-shared --with-incompatible-bdb"
#     - stage: ubuntu18
#       dist: bionic
#       env: >-
#         HOST=x86_64-86-linux-gnu
#         NAME=ubuntu18.04-$HOST
#         PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev libprotobuf-dev"
#         DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1"
#         GOAL="install"
#         BITCOIN_CONFIG="--disable-tests --disable-gui-tests --disable-bench --enable-experimental-asm CFLAGS=-fPIC CXXFLAGS=-fPIC --enable-shared --with-incompatible-bdb"
    - stage: windows32
      dist: bionic
      env: >-
        HOST=i686-w64-mingw32
        DPKG_ADD_ARCH="i386"
        DEP_OPTS="NO_QT=1"
        PACKAGES="python3 nsis g++-mingw-w64-i686 wine-binfmt wine32"
        GOAL="install"
        BITCOIN_CONFIG="--enable-reduce-exports"
      install:
        - travis_retry sudo apt-get install python3 nsis g++-mingw-w64-i686 wine-binfmt wine32 -y
